name = "account-pwd-manager"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "account-pwd-manager-prod"

[env.staging]
name = "account-pwd-manager-staging"

[[kv_namespaces]]
binding = "ACCOUNT_DATA"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[site]
bucket = "./src" 