name = "account-pwd-manager"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ACCOUNT_DATA"
id = "41873ec821814ed28aa4692fad60f69b"
preview_id = "41873ec821814ed28aa4692fad60f69b" 